project:
  type: book
  output-dir: _book

book:
  title: "LLMs in R"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-risks-ethics.qmd
    - part: "Getting Started"
      chapters:
        - 03-getting-started.qmd
        - 04-model-selection.qmd
        - 05-packages.qmd
    - part: "Security and Best Practices"
      chapters:
        - 06-fundamentals.qmd
        - 07-privacy.qmd
    - part: "Applications"
      chapters:
        - 08-code-gen.qmd
        - 09-data-analysis.qmd
        - 10-text-analysis.qmd
        - 11-shiny-apps.qmd
    - part: "Production and Advanced Topics"
      chapters:
        - 12-rag.qmd
        - 13-production.qmd
        - 14-education.qmd
        - 15-research.qmd
  appendices:
    - guidance/chapter_planning_template.qmd

editor: source

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    df-print: paged
    fig-width: 8
    fig-height: 6
    reader-mode: true
    repo-branch: main
    repo-actions: [source, issue]
    page-footer:
      right: |
        This book was built with <a href="https://quarto.org/">Quarto</a>.